services:
  mysql:
    image: mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: routed
      MYSQL_ROOT_PASSWORD: root
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-proot"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    restart: unless-stopped
    ports:
      - 3000:3000
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      MYSQL_URL: mysql://root:root@mysql:3306/routed
